Repository Fidelisaboke/nature-quest, pull requests merged in 2025-09, with the labels that each got.

#2 feat: project setup and initialisation
  .env.example
  DEMO.md
  docker-compose.yml
  nature-quest/.gitignore
  nature-quest/DEMO.md
  nature-quest/README.md
  nature-quest/backend/__init__.py
  nature-quest/backend/asgi.py
  nature-quest/backend/settings.py
  nature-quest/backend/urls.py
  nature-quest/backend/wsgi.py
  nature-quest/docker-compose.yml
  nature-quest/health/__init__.py
  nature-quest/health/admin.py
  nature-quest/health/apps.py
  nature-quest/health/migrations/__init__.py
  nature-quest/health/models.py
  nature-quest/health/tests.py
  nature-quest/health/views.py
  nature-quest/manage.py
  nature-quest/requirements.txt
  nature-quest/run-local.bat
  nature-quest/scripts/run-local.sh
  run-local
Labels: good first issue

#4 feat: restructure project architecture with postgresql and modern tooling
  .env.example
  .gitignore
  DEMO.md
  Dockerfile
  README.md
  apps/__init__.py
  apps/health/__init__.py
  apps/health/admin.py
  apps/health/apps.py
  apps/health/migrations/__init__.py
  apps/health/models.py
  apps/health/tests.py
  apps/health/urls.py
  apps/health/views.py
  backend/__init__.py
  backend/asgi.py
  backend/settings.py
  backend/urls.py
  backend/wsgi.py
  docker-compose.yml
  docs/DEVELOPMENT.md
  docs/SETUP.md
  manage.py
  nature-quest/.gitignore
  nature-quest/DEMO.md
  nature-quest/README.md
  nature-quest/backend/__init__.py
  nature-quest/backend/settings.py
  nature-quest/docker-compose.yml
  nature-quest/health/__init__.py
  nature-quest/health/admin.py
  nature-quest/health/apps.py
  nature-quest/health/migrations/__init__.py
  nature-quest/health/models.py
  nature-quest/health/tests.py
  nature-quest/health/views.py
  nature-quest/requirements.txt
  nature-quest/run-local.bat
  nature-quest/scripts/run-local.sh
  requirements.txt
  run-local
  scripts/run-local.sh
  scripts/setup-db.sh
Labels: enhancement, good first issue

#8 feat: add standardized API response and Swagger docs
  apps/common/__init__.py
  apps/common/responses/__init__.py
  apps/common/responses/api_responses.py
  apps/common/responses/schema_component.py
  apps/health/docs.py
  apps/health/serializers.py
  apps/health/views.py
  apps/users/apps.py
  apps/users/docs.py
  apps/users/serializer.py
  apps/users/serializers.py
  apps/users/urls.py
  apps/users/views.py
  backend/settings.py
  backend/urls.py
  nature-quest/.gitignore
Labels: documentation, enhancement, good first issue

#18 Backend configuration: settings, URLs, env example, and requirements …
  .env.example
  backend/settings.py
  backend/urls.py
  requirements.txt
Labels: enhancement
